language: php

php:
  - 5.5

install:
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer require codeclimate/php-test-reporter --dev
  - composer install --no-progress --no-interaction
  - sed -ie 's#\$opts\[CURLOPT_CONNECTTIMEOUT\] = 30;#\$opts\[CURLOPT_CONNECTTIMEOUT\] = 300;#g' vendor/pingplusplus/pingpp-php/lib/ApiRequestor.php
  - sed -ie 's#\$opts\[CURLOPT_TIMEOUT\] = 80;#\$opts\[CURLOPT_TIMEOUT\] = 800;#g' vendor/pingplusplus/pingpp-php/lib/ApiRequestor.php

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

addons:
  code_climate:
    repo_token: 50c5f39d1236ff659d85b678f01a72e15bd5f7f9b9dd44baadf560e1cc8dd90d

after_script:
  - vendor/bin/test-reporter
